export const services=[
["web-development","Website Development","BUILD","We design and develop fast, modern websites that make businesses look credible, explain their offer clearly and turn attention into action.","https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1600&q=88",["Business websites","Landing pages","E-commerce websites","Custom web applications","CMS integrations","Performance & SEO","Forms & lead capture","Third-party integrations"]],
["app-development","App / Mobile Development","BUILD","We turn useful ideas into polished mobile products with clean user experiences, reliable foundations and room to grow.","https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1600&q=88",["Product discovery","Mobile UI/UX","iOS & Android","API integration","Authentication","Dashboards","Notifications","Production-ready foundations"]],
["meta-ads","Meta Ads Management","GROW","We build and manage Facebook and Instagram advertising systems around the offer, creative, audience, tracking and conversion path.","https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1600&q=88",["Campaign strategy","Facebook & Instagram Ads","Creative testing","Lead generation","Sales campaigns","Retargeting","Pixel & CAPI support","Reporting & optimisation"]],
["graphics-design","Graphics Design","CREATE","We create digital-first graphics that make online businesses look established, consistent and ready to compete.","https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1600&q=88",["Social media graphics","Ad creatives","Brand identity assets","Campaign visuals","Product graphics","Carousels","Promotional designs","Marketing collateral"]],
["video-editing","Video Editing","MOVE","We edit short-form and marketing videos for attention, clarity and action across social platforms and paid campaigns.","https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1600&q=88",["Short-form video","Reels & TikTok","Ad editing","Captions & subtitles","Motion graphics","Talking-head edits","Content repurposing","Platform-ready exports"]],
["ai-automation","AI Automation","AUTOMATE","We design practical AI-powered workflows that reduce repetitive work, speed up operations and help teams do more with less manual effort.","https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=88",["AI assistants","Lead workflows","Content workflows","Data processing","CRM automation","Notifications","Internal tools","Workflow design"]],
["social-media","Social Media Management","STAY SEEN","We build consistent social content systems that keep your brand visible, useful and recognisable without posting just for the sake of posting.","https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1600&q=88",["Content strategy","Content calendars","Publishing","Community management","Platform optimisation","Analytics","Creative direction","Growth experiments"]]
];
export const projects=[
["nexora","Nexora Logistics","App Development","app-development","A production-style logistics mobile experience focused on shipment visibility, clear status information and operational simplicity.","https://images.unsplash.com/photo-1586528116493-da8b2e5f2e3a?auto=format&fit=crop&w=1600&q=88"],
["growth-system","Growth Campaign System","Meta Ads","meta-ads","A creative-led acquisition concept built around offer clarity, testing, retargeting and measurable lead generation.","https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=88"],
["commerce-web","E-commerce Experience","Web Development","web-development","A premium storefront direction designed around product discovery, trust, mobile usability and conversion.","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1600&q=88"],
["brand-creative","Digital Brand Creative","Graphics Design","graphics-design","A reusable creative direction for an online-first business across social posts, campaigns and promotional graphics.","https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=1600&q=88"],
["content-system","Short-form Content System","Video Editing","video-editing","A content editing direction for turning raw footage into clear, platform-ready short-form marketing content.","https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=1600&q=88"]
];
export const posts=[{id:"first-post",title:"Why good businesses still struggle to grow online",slug:"why-good-businesses-still-struggle-to-grow-online",excerpt:"A strong product is only the beginning. Growth gets easier when your website, creative and acquisition work as one system.",category:"Growth",date:"2026-10-01",author:"Smart Lead Systems",coverImage:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=88",content:"A business can have a good product and still stay invisible. The gap is often not quality; it is distribution, positioning and consistency.\n\nYour website should make the business credible. Your creative should make the offer easy to understand. Your paid acquisition should put the offer in front of the right people. When those pieces work together, marketing becomes a system instead of a collection of disconnected activities.\n\nThat is the thinking behind Smart Lead Systems: build the digital foundation, make the brand look the part, get the offer seen and keep improving the system."}];